<a href="https://colab.research.google.com/github/MateusMaartinS/pythonFag/blob/main/24_Arrays_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Arrays

## Numpy

Numpy é uma biblioteca Python voltada para computação científica. Possui implementações bastante otimizadas para utilização de *arrays* ou vetores.

Para que o acesso às estruturas seja possível, é necessário a importação da biblioteca. É comum e uma boa prática renomear a biblioteca para `np`.

**Exemplo**

```py
import numpy as np
```

In [ ]:
'''
Atividade

Importe a biblioteca numpy.
'''

import numpy as np

## arrays numpy

O **array** numpy é uma lista de valores, indexada por uma tupla de inteiros não negativos. O número de dimensões do **array** é também chamado de *rank* do **array**. O *shape* de um **array** é uma tupla de inteiros, dado o tamanho do **array** em cada dimensão definida. Nesta atividade, trataremos como sinônimos **array** e **vetor**.

Para criar um array, pode-se utilizar o método `.array()`.

**Exemplo**

Crie um vetor de uma dimensão

```py
a = np.array([1, 2, 3])
```

Para observar os tipos dos dados:

```py
print(a)
```

In [ ]:
a = np.array([1, 2, 3])
arr_py = [1, 2, 3]

print(a)
print(arr_py)

[1 2 3]
[1, 2, 3]


In [ ]:
print(a)

[1 2 3]


In [ ]:
'''
Atividade

Observe o tipo do dado do array e dos valores armazenados.
'''

print(type(a))
print(type(a[0]), type(a[1]),type(a[2]))

<class 'numpy.ndarray'>
<class 'numpy.int64'> <class 'numpy.int64'> <class 'numpy.int64'>


In [ ]:
'''
Atividade

Observe o formato do vetor.
'''

print (a.shape)

(3,)


Para acessar os elementos individualmente, pode-se utilizar a posição da mesma forma como é feito com sequências.

**Exemplo**

```py
print(a[0], a[1], a[2])
```

In [ ]:
'''
Atividade

Execute os códigos a seguir, e observe o resultado.
'''

print(a)
a[0]=100 #Altera o valor armazenado na posição 0
print(a)

[1 2 3]
[100   2   3]


Todos os dados armazenados devem ser do mesmo tipo. Caso não sejam, serão convertidos a um tipo em comum.

**Exemplo**

```py
arr_st = np.array(['a', 5.4, 2]) #todos os dados como string
arr_ft = np.array([1  , 5.4, 2]) #todos os dados como float

print(f'{arr_st}')
print(f'{arr_ft}')
```

In [ ]:
arr_st = np.array(['a', 5.4, 2]) #todos os dados como string
arr_ft = np.array([1  , 5.4, 2]) #todos os dados como float

print(f'{arr_st}')
print(f'{arr_ft}')

['a' '5.4' '2']
[1.  5.4 2. ]


In [ ]:
'''
Atividade

Crie um outro vetor, com o seguinte formato
'''

b = np.array([[1,2,3], [4,5,6]])

'''
Compare os arrays a e b. Qual é a diferença?
'''

print(b)
print(type(b[0][0]))

[[1 2 3]
 [4 5 6]]
<class 'numpy.int64'>


In [ ]:
'''
Atividade

Execute o código abaixo, e o quê é mostrado.
'''

print(b[1])
print(b[1][1])

[4 5 6]
5


## Reshape

É possível alterar o formato do **array**. Execute os código abaixo passo a passo, observando o resultado:

In [ ]:
arr = np.arange(10)
print(arr)
print(arr.shape)
print("reshape 1")
arr_reshaped_1 = arr.reshape(5,2)
print(arr_reshaped_1)
print(arr_reshaped_1.shape)
print("reshape 2")
print(arr.reshape(3,5))


[0 1 2 3 4 5 6 7 8 9]
(10,)
reshape 1
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
(5, 2)
reshape 2


ValueError: cannot reshape array of size 10 into shape (3,5)

### Sintaxe

`.reshape(l,c)`

onde:

* l: número de linhas
* c: número de colunas

O valor l*c deve corresponder à quantidade total de elementos no array.

É possível definir a ordem do array sem conhecer uma de suas dimensões. Para isto, basta substituir o número de linhas ou colunas por -1.

**Exemplo**

```py
arr = np.arange(10)
arr.reshape(5,-1)
arr.reshape(-1,5)
arr.reshape(2,-1)
arr.reshape(-1,2)
```

In [ ]:
arr = np.arange(10)
print(arr.reshape(5,-1))
print(arr.reshape(-1,5))
print(arr.reshape(2,-1))
print(arr.reshape(-1,2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
'''
Atividade

Crie um array com 100 elementos contendo inteiros em sequência.
Em seguida, organize esses valores em 10 colunas.
Organize o mesmo array em 25 colunas.
'''

arr = np.arange(100)

print(arr.reshape(-1,10))
print(arr.reshape(10,10))
#                 L  C
print(arr.reshape(-1,25))




[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]
 [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49]
 [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
  74]
 [75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98
  99]]


## Tipos de dados

**Exemplo**

Observe os tipos de dados armazenados

```py
print(a.dtype)
```

In [ ]:
a = np.array([1, 2, 3])
print(a.dtype)

int64


In [ ]:
'''
Atividade

Compare o resultado do código anterior com os tipos de dados dos vetores abaixo, e explique o que ocorreu.
'''

x=np.array([1, 2])
print(x.dtype)
y=np.array([1.0, 2.0])
print(y.dtype)
z=np.array([1.9, 2.0], dtype=np.int64, )
print(z.dtype)
print(z)

int64
float64
int64
[1 2]


## Criação de arrays

In [ ]:
'''
Atividade

Teste as funções abaixo, e observe o vetor retornado por cada função.
'''

np.zeros((2,2))
print(np.zeros((2,2)))
np.ones((3,3))
print(np.ones((3,3)))
np.full((4,4),9)
print(np.full((4,4),9))
np.eye(5)
print(np.eye(5))
np.random.random((6,6))
print(np.random.random((6,6)))

[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[9.66946029e-02 7.83472108e-01 6.30945425e-01 7.63960697e-01
  1.03959472e-01 4.93055275e-01]
 [5.78683564e-01 9.38203106e-01 7.25025413e-01 5.69250111e-01
  6.66288465e-01 4.92204791e-01]
 [8.37714202e-01 9.95745675e-01 9.10729655e-01 9.89075590e-01
  2.93838036e-03 5.66506636e-01]
 [3.97044022e-01 8.23633323e-01 3.82702315e-01 3.57426165e-01
  9.11635214e-01 9.77150128e-01]
 [1.41640171e-01 5.26242298e-01 5.85886775e-01 4.81546249e-02
  9.96500934e-01 4.14541207e-01]
 [4.41724520e-01 9.79962533e-01 4.79600966e-05 5.43227184e-01
  7.17524067e-01 3.58933972e-02]]


In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Outras funções podem ser utilizadas para obter valores igualmente espaçados entre si.

**Exemplo**

```py
np.linspace(0,10,5)
np.linspace(0,10,3)
np.linspace(0,10,11)
```

### Sintaxe

`.linspace(i,f,n)`

Onde:

* `i`: valor inicial
* `f`: valor final
* `n`: quantidade de valores no método `linspace`, os valores de saída são do tipo `float` (`numpy.float64`).

In [ ]:
np.linspace(0,10,5)
print(np.linspace(10,10,10))
np.linspace(0,10,11)

[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

## Slicing

Semelhantes às listas em Python, os arrays numpy possibilitam o slicing. Como os arrays podem possuir diversas dimensões, é necessário identificar o slice para cada dimensão.

```py
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]
```

Significado:

```py
:2: linhas 0 a 1  
1:3: colunas 1 a 2
```

In [ ]:
'''
Atividade

Observe o conteúdo dos vetores a e b.
'''
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(a)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#  l = 0 e 1
#  c = 1 e 2
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [ ]:
'''
Atividade

Como seria para mostrar apenas as colunas 1 e 3 utilizando slices?
'''

d = a[:,[1,3]]

print(d)



[[ 2  4]
 [ 6  8]
 [10 12]]


In [ ]:
'''
Atividade

Execute o código abaixo, e observe os resultados.
'''

b = a[[0,2], 2]
c = a[[0,2,2], [0,2,3]]

'''
- O que ocorreu em `b` e `c`?
'''
print(a)
#print(b)
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1 11 12]


## Alterações em slices

**Atividade**

Observe o array `a`

Execute:

```py
c = a[:2, 1:3]
```

Observe o array `c`

Execute:

```py
c[0][0]=20
```

Observe o array `a` e explique o resultado.

In [ ]:
c = a[:2, 1:3]
print(a)
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [ ]:
c[0][0] = 20
print(c)
print(a)

[[20  3]
 [ 6  7]]
[[ 1 20  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Operações sobre arrays

**Exemplo**

Arrays:

```py
x = np.array([ [1, 2],[3, 4] ])  
y = np.array([ [5, 6],[7, 8] ])  
print('x:',x)
print('y:',y)
```

Operações básicas podem ser realizadas sobre o array

* adição (+)
* subtração (-)
* multiplicação (*)
* divisão (/)

**Exemplo**

```py
x+y
x-y
x*y
x/y
```

A biblioteca numpy também possui outras operações, acessíveis por métodos:

```py
.add()
.subtract()
.multiply()
.divide()
.sqrt()
...
```

Exemplo

```py
np.add(x,4)
np.subtract(x,2)
np.multiply(x,5)
np.divide(x,2)
np.sqrt(x)
```

Possui também operações sobre os valores em arrays

```py
.sum()
.mean()
.min()
.max()
...
```

**Exemplo**

```py
x.sum()
x.mean()
x.min()
x.max()
```

Atividade

Realize as seguinte operações:

a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])  
b = np.array([0, 2, 0, 1])  
a[np.arange(4), b] += 10

Observe:

Quais são os conteúdos dos arrays a e b após a criação deles?
Qual é o resultado da expressão np.arange(4)?
Ao final, qual é o conteúdo do array a?
Quais posições de a foram alteradas?
Por que apenas essas posições foram alteradas?

In [ ]:


a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)
b = np.array([0, 2, 0, 1])
print(np.arange(4))
print(b)
a[np.arange(4), b] += 10
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[0 1 2 3]
[0 2 0 1]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [ ]:
x = np.array([ [1, 2],[3, 4] ])
y = np.array([ [5, 6],[7, 8] ])
print('x:\n',x)
print('y:\n',y)

print(x.max())

x:
 [[1 2]
 [3 4]]
y:
 [[5 6]
 [7 8]]
4


In [ ]:
'''
Atividade

Realize as seguinte operações:
'''

a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
b = np.array([0, 2, 0, 1])
a[np.arange(4), b] += 10

'''
Observe:

Quais são os conteúdos dos arrays a e b após a criação deles?
Qual é o resultado da expressão np.arange(4)?
[0 1 2 3]
Ao final, qual é o conteúdo do array a? Quais posições de a foram alteradas?
Por que apenas essas posições foram alteradas?
'''

## Índices booleanos

Numpy possibilita que sejam aplicadas operações a todos os elementos. Para operadores relacionais, é retornado um array booleano.

**Atividade**

Execute:

```py
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])  
idx = a > 6
```

Observe o conteúdo:

* do array `a`
* do array `idx`

Execute:

```py
a[idx]
```

Observe o resultado.

Execute:

```py
a[idx] += 100
```

Observe o resultado. O que aconteceu?

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
idx = a >= 6
print(a)
print(idx)
print(a[idx])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 6  7  8  9 10 11 12]


In [ ]:
'''
Atividade

Qual é a soma dos números com valor maior que 8 no array `a`?
Qual é a soma dos valores menores que 10 no array `a`?
'''

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(a[a<10].sum())

45


## Where

Utilizando a função `where()`, é possível descobrir quais posições do **array** correspondem a uma condição determinada.

**Exemplos**

Extrair valores maiores que 15:

```py
arr = np.arange(10,20)
np.where(arr > 15)
```

Extrair valores pares:

```py
arr = np.arange(10,20)
np.where(arr % 2 == 0)
```

In [ ]:
arr = np.arange(10,20)
print(arr)
print(np.where(arr > 15))

[10 11 12 13 14 15 16 17 18 19]
(array([6, 7, 8, 9]),)


In [ ]:
arr = np.arange(10,20)
np.where(arr % 2 == 0)

(array([0, 2, 4, 6, 8]),)

In [ ]:
'''
Atividade

Obtenha a posição do array que possui o maior valor.
'''
a[0][0] = 12
print(a)
print(a.max())
# np.where -> espera uma condição -> retorna posições que satisfaçam a condição
print(np.where(a == 13))
print(a[a>13])

[[12  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
(array([], dtype=int64), array([], dtype=int64))
[]


# Referências

[HARRIS. C.R. Millman, K.J, van der Walt, S.J. et al. Array programming with NumPy. Nature 585, 357-362, 2020 PDF](https://www.nature.com/articles/s41586-020-2649-2)

### **Comparando** tempo de execução em operação vanilla python vs numpy


In [ ]:
import numpy as np
import time

size = 1000

print(f"Comparando a adição de duas matrizes {size}x{size}")

np_matrix1 = np.random.rand(size, size)
np_matrix2 = np.random.rand(size, size)

start_time_np = time.time()
np_result = np_matrix1 + np_matrix2
end_time_np = time.time()
duration_np = end_time_np - start_time_np

print(f"\nTempo de execução com NumPy: {duration_np:.6f} segundos")

py_matrix1 = [[np.random.rand() for _ in range(size)] for _ in range(size)]
py_matrix2 = [[np.random.rand() for _ in range(size)] for _ in range(size)]
py_result = [[0 for _ in range(size)] for _ in range(size)] # Inicializa a matriz resultado

start_time_py = time.time()
for i in range(size):
    for j in range(size):
        py_result[i][j] = py_matrix1[i][j] + py_matrix2[i][j]
end_time_py = time.time()
duration_py = end_time_py - start_time_py

print(f"Tempo de execução com Listas Python: {duration_py:.6f} segundos")

if duration_np < duration_py:
    print(f"\nNumPy foi {duration_py / duration_np:.2f} vezes mais rápido que as listas Python.")
elif duration_py < duration_np:
    print(f"\nListas Python foram {duration_np / duration_py:.2f} vezes mais rápidas que NumPy. (Isso é improvável para essa operação e tamanho de matriz.)")
else:
    print("\nAmbos tiveram tempos de execução semelhantes.")


Comparando a adição de duas matrizes 1000x1000

Tempo de execução com NumPy: 0.003199 segundos
Tempo de execução com Listas Python: 0.256668 segundos

NumPy foi 80.24 vezes mais rápido que as listas Python.
